///|
pub extend Directive with Eq::{equal, not_equal}

///|
pub extend Directive with @debug.Debug::{to_repr}

///|
pub extend Config with Eq::{equal, not_equal}

///|
pub extend Config with @debug.Debug::{to_repr}

///|
pub extend NgxError with Eq::{equal, not_equal}

///|
pub extend NgxError with @debug.Debug::{to_repr}

///|
pub extend TokKind with Eq::{equal, not_equal}

///|
pub extend TokKind with @debug.Debug::{to_repr}

///|
pub extend Tok with Eq::{equal, not_equal}

///|
pub extend Tok with @debug.Debug::{to_repr}

///|
pub extend ConfigStats with Eq::{equal, not_equal}

///|
pub extend ConfigStats with @debug.Debug::{to_repr}
